from django.db import models


class LogEvent(models.Model):
    datetime = models.DateTimeField()
    event_type = models.CharField(max_length=100, null=True, blank=True)
    auth_type = models.CharField(max_length=100, null=True, blank=True)
    username = models.CharField(max_length=100, null=True, blank=True)
    ip_address = models.CharField(max_length=100, null=True, blank=True)
    port = models.IntegerField(null=True, blank=True)
    session_event = models.CharField(max_length=100, null=True, blank=True)
    session_username = models.CharField(max_length=100, null=True, blank=True)
    session_uid = models.IntegerField(null=True, blank=True)
    session_by_uid = models.IntegerField(null=True, blank=True)
    session_id = models.IntegerField(null=True, blank=True)
    sudo_fail_message = models.TextField(null=True, blank=True)
    connection_closed_username = models.CharField(max_length=100, null=True, blank=True)
    connection_closed_ip = models.CharField(max_length=100, null=True, blank=True)
    connection_closed_port = models.IntegerField(null=True, blank=True)
    received_disconnect_ip = models.CharField(max_length=100, null=True, blank=True)
    received_disconnect_port = models.IntegerField(null=True, blank=True)
    disconnected_username = models.CharField(max_length=100, null=True, blank=True)
    disconnected_ip = models.CharField(max_length=100, null=True, blank=True)
    disconnected_port = models.IntegerField(null=True, blank=True)
    auth_failure_username = models.CharField(max_length=100, null=True, blank=True)
    failed_password_username = models.CharField(max_length=100, null=True, blank=True)
    failed_password_ip = models.CharField(max_length=100, null=True, blank=True)
    failed_password_port = models.IntegerField(null=True, blank=True)
    sshd_listening_address = models.CharField(max_length=100, null=True, blank=True)
    sshd_listening_port = models.IntegerField(null=True, blank=True)
    new_session_logind_id = models.IntegerField(null=True, blank=True)
    new_session_logind_user = models.CharField(max_length=100, null=True, blank=True)
    session_logged_out_id = models.IntegerField(null=True, blank=True)
    session_removed_id = models.IntegerField(null=True, blank=True)
